#!/bin/bash
source /home/unreal/config
## dependencys

## Install anope
wget -O anope-$ANOPE_VERSION-source.tar.gz http://sourceforge.net/projects/anope/files/anope-stable/Anope%20$ANOPE_VERSION/anope-$ANOPE_VERSION-source.tar.gz/download 
# wget http://sourceforge.net/projects/anope/files/anope-stable/Anope%201.8.8/anope-1.8.8.tar.gz/download
tar -zxvf anope-$ANOPE_VERSION-source.tar.gz
cd anope-$ANOPE_VERSION-source
/usr/bin/expect /home/unreal/anope-make.expect
make
make install



cp /home/unreal/Unreal$UNREAL_VERSION/services/example.conf /home/unreal/Unreal$UNREAL_VERSION/services/services.conf
#Make a edit for unrealircd linking
#Run Anope:
#./services
